query Albums {
  allAlbums {
    id
    title
    type
    artist {
      id
      name
      photoUrl
      biography
      albums {
        id
      }
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

query Album($id: ID!) {
  oneAlbum(id: $id) {
    id
    title
    type
    artist {
      id
      name
      photoUrl
      biography
      albums {
        id
      }
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

query AlbumsByType($type: String) {
  albumsByType(type: $type) {
    id
    title
    type
    artist {
      id
      name
      photoUrl
      biography
      albums {
        id
      }
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

query AlbumsByTitle($title: String) {
  albumsByTitle(title: $title) {
    id
    title
    type
    artist {
      id
      name
      photoUrl
      biography
      albums {
        id
      }
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

query AlbumsByArtist($artist: String) {
  albumsByArtist(artist: $artist) {
    id
    title
    type
    artist {
      id
      name
      photoUrl
      biography
      albums {
        id
      }
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

mutation GenerateColors($imageUrl: String) {
  generateColors(imageUrl: $imageUrl) {
    colors
  }
}

mutation AddToLike($albumId: ID!) {
  addToLike(albumID: $albumId) {
    id
    title
    type
    artist {
      id
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

mutation RemoveFromLike($albumId: ID!) {
  removeFromLike(albumID: $albumId) {
    id
    title
    type
    artist {
      id
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

mutation AddAlbum($input: AlbumInput) {
  addAlbum(input: $input) {
    id
    title
    type
    artist {
      id
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

mutation UpdateAlbum($albumId: ID!, $input: AlbumInput) {
  updateAlbum(albumID: $albumId, input: $input) {
    id
    title
    type
    artist {
      id
    }
    albumArt
    likeCount
    description
    spotify
    apple
    colors
  }
}

mutation DeleteAlbum($albumId: ID!) {
  deleteAlbum(albumID: $albumId)
}

mutation AddArtist($input: ArtistInput) {
  addArtist(input: $input) {
    id
    name
    photoUrl
    biography
    albums {
      id
    }
  }
}

mutation UpdateArtist($artistId: ID!, $input: ArtistInput) {
  updateArtist(artistID: $artistId, input: $input) {
    id
    name
    photoUrl
    biography
    albums {
      id
    }
  }
}

mutation DeleteArtist($artistId: ID!) {
  deleteArtist(artistID: $artistId)
}

mutation LogIn($password: String!, $username: String!) {
  logIn(password: $password, username: $username)
}
