import Head from "next/head";
import React from "react";

import { Loader } from "@/components/common/Loader";
import { Album } from "@/components/home/Album";
import { useHomePage } from "@/components/home/controller";

export default function Home() {
  const controller = useHomePage();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-between min-h-screen p-2">
        {/* <Loader /> */}

        <div className="grid grid-cols-1 gap-2 md:grid-cols-4 2xl:grid-cols-5">
          {controller?.albums?.map((album) => (
            <Album key={album.id} {...album} />
          ))}
        </div>

        {controller.isLoading && <Loader />}

        <div
          style={{ height: "2rem" }}
          ref={controller.ref}
          aria-hidden="true"
        />
      </main>
    </>
  );
}
